const defaultIdeas = [
  {
    text: 'Learn to pogostick',
    categories: ['outdoor'],
    id: 0,
    icon: '⛰',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Do a puzzle',
    categories: ['indoor'],
    id: 1,
    icon: '🧩',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Plant a garden',
    categories: ['outdoor'],
    id: 2,
    icon: '🌱',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Walk the dog',
    categories: ['outdoor', 'pets'],
    id: 3,
    icon: '🐕',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Learn to pogostick',
    categories: ['outdoor'],
    id: 4,
    icon: '⛰',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Do a puzzle',
    categories: ['indoor'],
    id: 5,
    icon: '🧩',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Plant a garden',
    categories: ['outdoor'],
    id: 6,
    icon: '🌱',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Walk the dog',
    categories: ['outdoor', 'pets'],
    id: 7,
    icon: '🐕',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Learn to pogostick',
    categories: ['outdoor'],
    id: 8,
    icon: '⛰',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Do a puzzle',
    categories: ['indoor'],
    id: 9,
    icon: '🧩',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Plant a garden',
    categories: ['outdoor'],
    id: 10,
    icon: '🌱',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Walk the dog',
    categories: ['outdoor', 'pets'],
    id: 11,
    icon: '🐕',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Learn to pogostick',
    categories: ['outdoor'],
    id: 12,
    icon: '⛰',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Do a puzzle',
    categories: ['indoor'],
    id: 13,
    icon: '🧩',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Plant a garden',
    categories: ['outdoor'],
    id: 14,
    icon: '🌱',
    disliked: false,
    liked: false,
    isCustom: false,
  },
  {
    text: 'Walk the dog',
    categories: ['outdoor', 'pets'],
    id: 15,
    icon: '🐕',
    disliked: false,
    liked: false,
    isCustom: false,
  },
];

export default defaultIdeas;
